'use client'

import { Scale, ShieldAlert, Cpu, Database, Gavel } from 'lucide-react'
import Link from 'next/link'

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
                <div className="bg-[#002776] px-8 py-10 text-white relative overflow-hidden">
                    <div className="absolute inset-0 opacity-10 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] mix-blend-overlay"></div>
                    <Scale className="w-12 h-12 mb-4 text-[#92d400] relative z-10" />
                    <h1 className="text-3xl font-black tracking-tight relative z-10">Terms of Service</h1>
                    <p className="mt-2 text-blue-100 font-medium relative z-10">Arkashri Technologies Private Limited | Effective Date: April 2026</p>
                </div>
                
                <div className="p-8 prose prose-slate max-w-none prose-h2:text-[#002776] prose-a:text-blue-600 prose-li:my-0.5 text-sm">
                    <div className="bg-blue-50 border-l-4 border-blue-500 p-4 mb-8 text-blue-900 rounded-r">
                        <strong>Platform Definition:</strong> Arkashri is a governed, AI‑assisted <strong>audit and compliance infrastructure platform</strong>. It provides configurable workflow orchestration, data normalization, analytical signaling, and tamper‑evident recordkeeping. Arkashri <strong>does not perform audits</strong>, does not determine audit scope, materiality, conclusions, or opinion outcomes, and does not issue certifications, legal advice, or regulatory approvals. All outputs generated by the Platform are <strong>assistive, non‑final computational artifacts</strong> and may not be relied upon as the sole or primary basis for any professional or legal decision. All professional judgment, validation, and final conclusions remain solely with licensed Users.
                    </div>

                    <h2 className="flex items-center gap-2"><Gavel className="w-5 h-5"/> 1. Master Non‑Audit Clause (Non-Negotiable)</h2>
                    <p>Arkashri operates strictly as technology infrastructure, not as an audit or compliance authority. Arkashri <strong>does not autonomously determine, initiate, or finalize any audit step</strong>, and all outputs remain contingent on User-controlled inputs and approvals. Any default workflows or risk thresholds provided by Arkashri are illustrative only and do not constitute recommended or required audit practices.</p>

                    <h2 className="flex items-center gap-2 mt-8"><Cpu className="w-5 h-5"/> 2. Scope of Service & Restrictions</h2>
                    <p>Arkashri’s services may include workflow orchestration, data import/reconciliation, AI‑assisted analysis and anomaly detection, report drafting support, evidence aggregation, multi‑party signature workflows, and cryptographic audit trail anchoring. Arkashri does <strong>not</strong> provide any certified audit opinion, nor guarantee detection of fraud or errors.</p>
                    
                    <p><strong>Human-in-the-Loop Controls:</strong> The Platform enforces mandatory <strong>Judgment Gates</strong>, which are checkpoints for User validation and do not impose or substitute professional decision-making authority. No “Sealed Audit” is issued without explicit human sign‑off. This term <strong>does not imply</strong> regulatory certification, completion of a formal audit, or guarantee of correctness.</p>

                    <p><strong>AI Limitations and Disclaimer:</strong> AI Outputs (e.g., risk scores, flagged items) are probabilistic and non‑deterministic. Identical inputs may produce different outputs. AI-generated suggestions may be incomplete or contain hallucinations. Users agree that Arkashri shall not be liable for outcomes arising from reliance on AI outputs without independent validation. The Platform is provided <em>“as is”</em> without warranties. Outputs should be reviewed by qualified professionals.</p>

                    <h2 className="flex items-center gap-2 mt-8"><Database className="w-5 h-5"/> 3. Data Ownership & DPDP Compliance</h2>
                    <p>Users retain all ownership of their uploaded content and data. Arkashri does not claim any IP rights in User data. By uploading data, Users warrant they have lawful rights and consents.</p>
                    <p>Under the Digital Personal Data Protection Act 2023, Arkashri is a <strong>Data Processor</strong> for Audit Data processed strictly on behalf of the User. Arkashri’s processing of Audit Data is purely technical, performed under User instructions. Arkashri does not determine the purposes or means of processing User data. Arkashri will not use customer data to train public AI models.</p>

                    <h2 className="flex items-center gap-2 mt-8"><ShieldAlert className="w-5 h-5"/> 4. Blockchain Anchoring (Bharatiya Sakshya Adhiniyam)</h2>
                    <p>Blockchain anchoring and hashes <strong>only verify the integrity of records</strong>. They do not attest to the accuracy or truth of the content in those records. Logs provide integrity verification only. We make no representations that any system is absolutely immune from compromise.</p>

                    <h2 className="mt-8">5. Liability, Indemnification & General Provisions</h2>
                    <p><strong>Limitation of Liability:</strong> Arkashri’s fees reflect a shared‑risk, low‑cost infrastructure model. Users acknowledge that Arkashri’s platform fees do not encompass professional risk insurance. To the maximum extent permitted by law, Arkashri’s total liability for all claims is capped at the lesser of (a) the fees paid in the three (3) months prior to the claim, or (b) INR 10,000. This cap excludes liability that cannot be limited by law.</p>
                    <p><strong>Duty of Care Disclaimer:</strong> Arkashri does not assume any fiduciary, advisory, or professional duty to Users or third parties. The Platform is a tool; all professional responsibility remains with the User.</p>
                    <p><strong>Indemnification:</strong> Users will indemnify and hold harmless Arkashri against any claim arising from (a) the User’s misuse of the Platform, (b) uploading unlawful data, (c) violation of third-party rights, or (d) reliance on outputs without proper verification.</p>
                    <p><strong>Dispute Resolution:</strong> Governed by Indian law. Disputes will be arbitrated in New Delhi under India’s Arbitration and Conciliation Act. Delhi courts have exclusive jurisdiction for non‑arbitrable matters.</p>

                    <div className="mt-10 pt-6 border-t border-gray-100 flex gap-4 justify-end">
                        <Link href="/privacy" className="text-gray-500 hover:text-[#002776] px-4 py-2 font-medium transition-colors">Privacy Notice</Link>
                        <Link href="/cookies" className="text-gray-500 hover:text-[#002776] px-4 py-2 font-medium transition-colors">Cookies Policy</Link>
                        <Link href="/dashboard" className="bg-[#002776] text-white px-6 py-2 rounded-lg font-bold hover:bg-[#001a54] transition-colors shadow-md">
                            Acknowledge
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    )
}
