import { ShieldAlert } from 'lucide-react'

export function DisclaimerBadge({ aiConfidence }: { aiConfidence?: number }) {
  return (
    <div className="relative group inline-flex items-center gap-1.5 px-2 py-1 rounded-md bg-amber-50 border border-amber-200 text-amber-800 text-[10px] font-bold uppercase tracking-wider cursor-help transition-colors hover:bg-amber-100 max-w-full">
      <ShieldAlert className="w-3.5 h-3.5 text-amber-600 shrink-0" />
      <span className="truncate">AI-Assisted — Human Review Required</span>

      {/* Tooltip Content (Visible on Hover) */}
      <div className="absolute top-full right-0 mt-2 w-64 md:w-72 pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity z-50">
        <div className="bg-white text-slate-800 border border-slate-200 shadow-xl p-3 font-medium text-xs leading-relaxed rounded-md whitespace-normal normal-case tracking-normal">
          <p className="mb-2">
            <strong>Legal Disclaimer:</strong> This output was generated by the Arkashri Decision Engine. It constitutes decision support only and does not represent a professional audit opinion.
          </p>
          <p className="text-slate-500">
            All outputs must be reviewed and confirmed by a registered Chartered Accountant before use.
            {aiConfidence && <span className="block mt-1 font-bold text-indigo-600">Confidence Score: {aiConfidence}%</span>}
          </p>
        </div>
      </div>
    </div>
  )
}

